### ISSUE TITLE
No example

### ISSUE THREAD

**Issue by Abraham1220** [cretl/gs1200hp-ctrl#1]
Hi!

Miss your curl examples of setting the PoE bits. Please add it to your library!

Thanks!

**Comment by Abraham1220** [comment]
Figured out in the meantime that I use the latest firmware on the switch which requires to save cookies. So the examples using "curl" are not working anymore. Prototyped a perl script using LWP::UserAgent and HTTP::CookieJar::LWP which works.

**Comment by cretl** [comment]
I just uploaded the new version of the script. It does support the newest firmware version (V2.00(ABKN.0)C0) and the cookie-based login.
